[project]
name = "src"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.6",
    "pyserial>=3.5",
    "websocket-client>=1.9.2",
]

[dependency-groups]
dev = [
    "micropython-esp32-stubs>=1.29.0.post1",
]
